### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by aavarghese** [operator-framework/operator-sdk-samples#129]
Running target `make test-e2e` is failing for all different options in there. Can someone else please confirm and let me know why this is happening?

**Comment by camilamacedo86** [comment]
hi @ansuabraham, 

First at al would be required to provide the errors that you are facing with it. Could you please let us know?

**Comment by ansuabraham** [comment]
Hi @camilamacedo86 
Sorry about that. Should have posted my error report in my original post. Here it is:

make test-e2e
... Running the same e2e tests with different args ...
... Running locally ...
kubectl create namespace memcached || true
namespace/memcached created
operator-sdk test local ./test/e2e --up-local --namespace=memcached
INFO[0000] Testing operator locally.                    
**flag provided but not defined: -singleNamespace**
Usage of /var/folders/_1/t4bj9rf51gq1bz38qgw40c1m0000gn/T/go-build661435375/b001/e2e.test:
  -globalMan string
    	path to operator manifest
  -kubeconfig string
    	path to kubeconfig
  -localOperator
    	enable if operator is running locally (not in cluster)
  -localOperatorArgs string
    	flags that the operator needs (while using --up-local). example: "--flag1 value1 --flag2=value2"
  -namespacedMan string
    	path to rbac manifest
  -root string
    	path to project root
  -skipCleanupOnError
    	If set as true, the cleanup function responsible to remove all artifacts will be skipped if an error is faced.
  -test.bench regexp
    	run only benchmarks matching regexp
  -test.benchmem
    	print memory allocations for benchmarks
  -test.benchtime d
    	run each benchmark for duration d (default 1s)
  -test.blockprofile file
    	write a goroutine blocking profile to file
  -test.blockprofilerate rate
    	set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
    	run tests and benchmarks n times (default 1)
  -test.coverprofile file
    	write a coverage profile to file
  -test.cpu list
    	comma-separated list of cpu counts to run each test with
  -test.cpuprofile file
    	write a cpu profile to file
  -test.failfast
    	do not start new tests after the first test failure
  -test.list regexp
    	list tests, examples, and benchmarks matching regexp then exit
  -test.memprofile file
    	write an allocation profile to file
  -test.memprofilerate rate
    	set memory allocation profiling rate (see runtime.MemProfileRate)
  -test.mutexprofile string
    	write a mutex contention profile to the named file after execution
  -test.mutexprofilefraction int
    	if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
  -test.outputdir dir
    	write profiles to dir
  -test.parallel n
    	run at most n tests in parallel (default 16)
  -test.run regexp
    	run only tests and examples matching regexp
  -test.short
    	run smaller test suite to save time
  -test.testlogfile file
    	write test action log to file (for use only by cmd/go)
  -test.timeout d
    	panic test binary after duration d (default 0, timeout disabled)
  -test.trace file
    	write an execution trace to file
  -test.v
    	verbose: print additional output
FAIL	github.com/operator-framework/operator-sdk-samples/go/memcached-operator/test/e2e	0.401s
FAIL
make: [test-e2e] Error 1 (ignored)
... Running NOT in parallel ...
operator-sdk test local ./test/e2e --go-test-flags "-v -parallel=1"
INFO[0000] Testing operator locally.                    
=== RUN   TestMemcached
=== RUN   TestMemcached/memcached-group
=== RUN   TestMemcached/memcached-group/Cluster
=== PAUSE TestMemcached/memcached-group/Cluster
=== CONT  TestMemcached/memcached-group/Cluster
--- FAIL: TestMemcached (8.20s)
    --- FAIL: TestMemcached/memcached-group (0.00s)
        --- FAIL: TestMemcached/memcached-group/Cluster (5.93s)
            client.go:62: resource type ServiceAccount with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) created
            client.go:62: resource type Role with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) created
            client.go:62: resource type RoleBinding with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) created
            client.go:62: resource type Deployment with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) created
            memcached_test.go:100: Initialized cluster resources
            **memcached_test.go:108: an empty namespace may not be set when a resource name is provided**
            client.go:83: resource type Deployment with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) successfully deleted
            client.go:83: resource type RoleBinding with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) successfully deleted
            client.go:83: resource type Role with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) successfully deleted
            client.go:83: resource type ServiceAccount with namespace/name (osdk-e2e-9ca2b8e4-2471-4dda-8499-8a989c5a6bfe/memcached-operator) successfully deleted
FAIL
FAIL	github.com/operator-framework/operator-sdk-samples/go/memcached-operator/test/e2e	11.015s
FAIL
make: [test-e2e] Error 1 (ignored)
... Running in parallel ...
operator-sdk test local ./test/e2e --go-test-flags "-v -parallel=2"
INFO[0000] Testing operator locally.                    
=== RUN   TestMemcached
=== RUN   TestMemcached/memcached-group
=== RUN   TestMemcached/memcached-group/Cluster
=== PAUSE TestMemcached/memcached-group/Cluster
=== CONT  TestMemcached/memcached-group/Cluster
--- FAIL: TestMemcached (7.84s)
    --- FAIL: TestMemcached/memcached-group (0.00s)
        --- FAIL: TestMemcached/memcached-group/Cluster (5.88s)
            client.go:62: resource type ServiceAccount with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) created
            client.go:62: resource type Role with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) created
            client.go:62: resource type RoleBinding with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) created
            client.go:62: resource type Deployment with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) created
            memcached_test.go:100: Initialized cluster resources
            **memcached_test.go:108: an empty namespace may not be set when a resource name is provided**
            client.go:83: resource type Deployment with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) successfully deleted
            client.go:83: resource type RoleBinding with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) successfully deleted
            client.go:83: resource type Role with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) successfully deleted
            client.go:83: resource type ServiceAccount with namespace/name (osdk-e2e-e189e62a-683a-4acf-a7cd-22635796b4ba/memcached-operator) successfully deleted
FAIL
FAIL	github.com/operator-framework/operator-sdk-samples/go/memcached-operator/test/e2e	10.085s
FAIL
make: [test-e2e] Error 1 (ignored)
... Running without options/args ...
operator-sdk test local ./test/e2e
INFO[0000] Testing operator locally.                    
--- FAIL: TestMemcached (8.02s)
    --- FAIL: TestMemcached/memcached-group (0.00s)
        --- FAIL: TestMemcached/memcached-group/Cluster (5.97s)
            client.go:62: resource type ServiceAccount with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) created
            client.go:62: resource type Role with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) created
            client.go:62: resource type RoleBinding with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) created
            client.go:62: resource type Deployment with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) created
            memcached_test.go:100: Initialized cluster resources
            **memcached_test.go:108: an empty namespace may not be set when a resource name is provided**
            client.go:83: resource type Deployment with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) successfully deleted
            client.go:83: resource type RoleBinding with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) successfully deleted
            client.go:83: resource type Role with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) successfully deleted
            client.go:83: resource type ServiceAccount with namespace/name (osdk-e2e-2dc4545e-f1bb-40cc-86cc-37e4b583ee5e/memcached-operator) successfully deleted
FAIL
FAIL	github.com/operator-framework/operator-sdk-samples/go/memcached-operator/test/e2e	10.439s
FAIL
make: [test-e2e] Error 1 (ignored)
... Running with the --debug param ...
operator-sdk test local ./test/e2e --debug
INFO[0000] Testing operator locally.                    
--- FAIL: TestMemcached (7.96s)
    --- FAIL: TestMemcached/memcached-group (0.00s)
        --- FAIL: TestMemcached/memcached-group/Cluster (5.97s)
            client.go:62: resource type ServiceAccount with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) created
            client.go:62: resource type Role with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) created
            client.go:62: resource type RoleBinding with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) created
            client.go:62: resource type Deployment with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) created
            memcached_test.go:100: Initialized cluster resources
            **memcached_test.go:108: an empty namespace may not be set when a resource name is provided**
            client.go:83: resource type Deployment with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) successfully deleted
            client.go:83: resource type RoleBinding with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) successfully deleted
            client.go:83: resource type Role with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) successfully deleted
            client.go:83: resource type ServiceAccount with namespace/name (osdk-e2e-72010101-b362-4aca-b7fb-1662a1790f7a/memcached-operator) successfully deleted
FAIL
FAIL	github.com/operator-framework/operator-sdk-samples/go/memcached-operator/test/e2e	10.330s
FAIL
make: [test-e2e] Error 1 (ignored)
... Running with the --verbose param ...
operator-sdk test local ./test/e2e --verbose
DEBU[0000] Debug logging is set                         
INFO[0000] Testing operator locally.                    
DEBU[0000] Running []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/var/folders/_1/t4bj9rf51gq1bz38qgw40c1m0000gn/T/namespaced-manifest.yaml102543468", "-globalMan", "/var/folders/_1/t4bj9rf51gq1bz38qgw40c1m0000gn/T/global-manifest.yaml719167195", "-root", "/Users/ansuvarghese/go/src/github.com/operator-framework/operator-sdk-samples/go/memcached-operator"} 
=== RUN   TestMemcached
=== RUN   TestMemcached/memcached-group
=== RUN   TestMemcached/memcached-group/Cluster
=== PAUSE TestMemcached/memcached-group/Cluster
=== CONT  TestMemcached/memcached-group/Cluster
--- FAIL: TestMemcached (8.03s)
    --- FAIL: TestMemcached/memcached-group (0.00s)
        --- FAIL: TestMemcached/memcached-group/Cluster (5.91s)
            client.go:62: resource type ServiceAccount with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) created
            client.go:62: resource type Role with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) created
            client.go:62: resource type RoleBinding with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) created
            client.go:62: resource type Deployment with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) created
            memcached_test.go:100: Initialized cluster resources
            **memcached_test.go:108: an empty namespace may not be set when a resource name is provided**
            client.go:83: resource type Deployment with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) successfully deleted
            client.go:83: resource type RoleBinding with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) successfully deleted
            client.go:83: resource type Role with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) successfully deleted
            client.go:83: resource type ServiceAccount with namespace/name (osdk-e2e-0a8b30bc-2334-4a77-beb8-4ffdf8648226/memcached-operator) successfully deleted
FAIL
FAIL	github.com/operator-framework/operator-sdk-samples/go/memcached-operator/test/e2e	10.567s
FAIL
make: [test-e2e] Error 1 (ignored)

**Comment by camilamacedo86** [comment]
Hi @aavarghese, 


SDK is in a process to be integrated with KB which means that its project layouts will be aligned. More info : [Integrating Kubebuilder and Operator SDK](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md). So, it will no longer exist for the new layout. In this way, I am closing this one. However, if you be facing any issue in your project that you needs our help please feel free to raise an issue in teh SDK repo.
