### ISSUE TITLE
Unable to run new layout project. 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk-samples#132]
I am following the [readme](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/kubebuilder/memcached-operator/README.md) steps and then I am facing the following issues:

- The error ` *** No rule to make target 'quay.io/camilamacedo86/memcached-operator:v0.0.1'.` is faced when the `$ make docker-build $IMG` is executed.
- The following error when ` make deploy $IMG` is executed:

```
$  make deploy $IMG
/Users/camilamacedo/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && kustomize edit set image controller=quay.io/camilamacedo86/memcached-operator:v0.0.1
kustomize build config/default | kubectl apply -f -
unable to recognize "STDIN": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"
make: *** [Makefile:46: deploy] Error 1
```

**Comment by camilamacedo86** [comment]
c/c @bharathi-tenneti @hasbro17 @jmrodri @estroz

**Comment by simrandhaliw** [comment]
I am also facing the exact same issue.

**Comment by bharathi-tenneti** [comment]
@camilamacedo86 Did you install cert-manager on the cluster? I know the README here does not state that.

**Comment by estroz** [comment]
The make invocation should be:
```sh
$ make deploy IMG=$IMG
```

**Comment by camilamacedo86** [comment]
HI @bharathi-tenneti I follow up the readme steps. Also, I did the fix described by @estroz before as well. So, if it is missing steps, could you please give a hand by adding then?

**Comment by simrandhaliw** [comment]
Testing this out with proper invocation, and having installed cert-manager on my cluster, I get this error when executing `make deploy $IMG`:
`
Error from server (InternalError): error when creating "config/samples/cache_v1alpha1_memcached.yaml": Internal error occurred: failed calling webhook "mmemcached.kb.io": Post https://memcached-operator-webhook-service.memcached-operator-system.svc:443/mutate-cache-example-com-v1alpha1-memcached?timeout=30s: no endpoints available for service "memcached-operator-webhook-service"`

**Comment by bharathi-tenneti** [comment]
@camilamacedo86 @simrandhaliw I was able to reproduce the issue.
As this particularly  example was extended to showcase `webhooks`, "certmanager" is required to install on the cluster.
Once this step is done, pre-deployment of the CR, the deployment is successfully created, and webhooks are also created. 
I will update the README with the missing step.

**Comment by camilamacedo86** [comment]
It is great @bharathi-tenneti  really tks.

**Comment by simrandhaliw** [comment]
Great, thanks.
