### ISSUE TITLE
Helm operator sample fails during 'make deploy' with 'no matches for kind "ServiceMonitor"'

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk-samples#150]
I found that in the Go sample operator, I had to install `cert-manager` into the cluster before deploying (see #149). For the Helm operator, I'm getting a similar error but concerning a `ServiceManager`:

```
error: unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
make: *** [deploy] Error 1
```

I was reading through the Helm operator sample README and didn't see anywhere a mention of extra software or configuration I'd have to deploy to my cluster to be able to deploy the sample operator, but it seems like something is missing (maybe there's a `ServiceMonitor` set up by default in some types of clusters, like OpenShift, that aren't available in vanilla Kubernetes?).

Related: https://github.com/geerlingguy/operator-sdk-performance-testing/issues/1

**Comment by geerlingguy** [comment]
It looks like I might need to deploy Prometheus Operator into the cluster? See: https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html

**Comment by geerlingguy** [comment]
PR #152 documents the requirement.

**Comment by camilamacedo86** [comment]
hi @geerlingguy, 

Also, see that the idea is to deprecate this one. More info: https://github.com/operator-framework/operator-sdk-samples/pull/163.  

I am closing this one. However, please feel free to raise issues against the SDK repo if you need. hi @geerlingguy, 

Also, see that the idea is to deprecate this one. More info: https://github.com/operator-framework/operator-sdk-samples/pull/163.  

I am closing this one. However, please feel free to raise issues against the SDK repo if you need.
