### ISSUE TITLE
Add reconciliation status to Go sample operator?

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk-samples#153]
When I'm working with the Ansible sample operator, I get the following status data out of CRs managed by it for free:

```
$ kubectl describe Memcached
...
Status:
  Conditions:
    Ansible Result:
      Changed:             0
      Completion:          2020-08-27T17:29:40.270243
      Failures:            0
      Ok:                  2
      Skipped:             0
    Last Transition Time:  2020-08-27T17:29:18Z
    Message:               Awaiting next reconciliation
    Reason:                Successful
    Status:                True
    Type:                  Running
```

The Helm sample also provides some nice output:

```
Status:
  Conditions:
    Last Transition Time:  2020-08-27T20:09:14Z
    Status:                True
    Type:                  Initialized
    Last Transition Time:  2020-08-27T20:09:30Z
    Message:               Memcached can be accessed via port 11211 [...]
    Reason:  InstallSuccessful
    Status:  True
    Type:    Deployed
```

On the other hand, if I look at a Memcached CR that is created with the Go sample, it gives me no relevant reconciliation status data, and so I'm left to other means to try to figure out if it's ready or still reconciling. There is a `Status.Node.[pod identifier]` that is appended in _some_, but not _all_ cases, to the data for a Memcached resource with the Go sample, but it is not obvious where in the lifecycle that is appended:

```
$ kubectl describe Memcached
...
Status:
  Nodes:
    memcached-756b6468d8-qqqh4
```

Is it possible to add some sort of reconciliation status data to the `Status` on the Go sample?

**Comment by geerlingguy** [comment]
The impetus for this issue is to benchmark how long it takes to complete reconciliation in different scenarios, specifically this issue for now: https://github.com/geerlingguy/operator-sdk-performance-testing/issues/3

**Comment by camilamacedo86** [comment]
Hi @geerlingguy, 

The Go project came from Kubebuider. Note that would recommend users implement conditional to check the status. However, see that the idea is to deprecate this one. More info: https://github.com/operator-framework/operator-sdk-samples/pull/163.  

And then, that has an open proposal for controller-runtime related to it https://github.com/kubernetes-sigs/controller-runtime/issues/1036 and might be helpful you follow up the issue raised in the SDK which motivates that https://github.com/operator-framework/operator-sdk/issues/3310. 

I am closing this one. However, please feel free to raise issues against the SDK repo if you need.
