### ISSUE TITLE
Use the same Pod labels across all three samples?

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk-samples#154]
I'm trying to write some automation that works across all three of the samples (Ansible, Go, and Helm), and right now it seems Ansible and Go assign the label `app=memcached` to the Memcached Pods, which is nice... but the Helm operator assigns the label `app.kubernetes.io/name=memcached`.

Is there any particular reason for this? I have to add special cases in my code to account for the fact the Helm sample is unique—there are some other oddities too, but this is the main one that's been causing me pain.

**Comment by geerlingguy** [comment]
(Additionally, and this may be a separate issue—the Ansible and Go operator examples use `size` in the spec to indicate how many instances of Memcached should be running for a given CR, whereas the Helm operator example uses `replicaCount`. Could we get that to be uniform across the three?)

**Comment by camilamacedo86** [comment]
hi @geerlingguy, 

Also, see that the idea is to deprecate this one. More info: https://github.com/operator-framework/operator-sdk-samples/pull/163.  

I am closing this one. However, please feel free to raise issues against the SDK repo if you need.
