### ISSUE TITLE
Helm sample operator default memory limit results in many OOMKilled restarts

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk-samples#156]
I'm trying to deploy the sample operators to a variety of Kubernetes clusters, and it seems like of all the three, Helm seems to have trouble when deployed to both Kind and Minikube clusters locally.

The cluster has tons of free memory available, but the controller/manager pod keeps restarting. When I go to describe the pod, I see a lot of:

```
$ kubectl describe pod -n memcached-operator-system memcached-operator-controller-manager-6d57f5fd7-gfnxw
...
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Mon, 31 Aug 2020 16:32:42 -0500
      Finished:     Mon, 31 Aug 2020 16:33:08 -0500
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     100m
      memory:  90Mi
    Requests:
      cpu:        100m
      memory:     60Mi
```

And it only reconciles a one or zero CR instances before it's killed and restarts itself.

After raising the Deployment's `Limits.memory` to `256Mi`, it seemed to work fine with no restarts.

**Comment by camilamacedo86** [comment]
hi @geerlingguy, 

Also, see that the idea is to deprecate this one. More info: https://github.com/operator-framework/operator-sdk-samples/pull/163. and then, IHMO the best way to address it would be via docs in the FAQ as commented in https://github.com/operator-framework/operator-sdk-samples/pull/157#issuecomment-684078545.

I am closing this one. However, please feel free to raise issues against the SDK repo if you need.
