### ISSUE TITLE
Update sample ansible-operator projects for layout changes

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk-samples#40]
After the controller-runtime refactor we changed the project layout and moved around some manifests around.
Specifically:
- `tmp/build`==>`build`
- `deploy/rbac.yaml`==> `deploy/role.yaml` and `deploy/role_binding.yaml`
- `deploy/cr.yaml` and `deploy/crd.yaml` ==> `deploy/crd/...`

@dymurray @shawn-hurley We should probably update the ansible examples to be in sync with the changes on the master.

**Comment by johnkim76** [comment]
@hasbro17 I'm working on updating the Ansible Examples. please assign this issue to me thank you.

**Comment by hasbro17** [comment]
@johnkim76 You're not showing up in the assignees tab but you're effectively assigned to this. Thanks.

/assign @johnkim76
