### ISSUE TITLE
Include a sample with multiple APIs defined

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk-samples#43]
With the latest master and the upcoming `v0.1.0` version of the SDK, the SDK will support projects with multiple APIs. A sample should be created (or an existing one updated) to demonstrate how to create and use multiple APIs with the SDK.

**Comment by camilamacedo86** [comment]
Hi @AlexNPavel, 

What do you mean with multiple APIs? Should it be to have more than one group?

**Comment by camilamacedo86** [comment]
SDK is moving for a new layout and then, we might start to generate the samples via the SDK repo as well which would allow us easier have a testdata with support for multigroup support such as : https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v3-multigroup. 

So, I am closing this one. however, feel free to re-open if you see that it is required.
