### ISSUE TITLE
Bump memcached sample operator to operator-sdk v0.10.0

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk-samples#68]
Now that the release is out, we should update the go example to use [operator-sdk v0.10.0.](https://github.com/operator-framework/operator-sdk/releases/tag/v0.10.0)

cc @estroz @hasbro17 @AlexNPavel 
We also said we want to somehow tag these example with releases, but that's outside the scope of this issue.

**Comment by camilamacedo86** [comment]
Done. 👍
