### ISSUE TITLE
Memcached-operator should provide an example of multiple CRD versions and a conversion webhook

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk-samples#69]
With the documentation for upgrading a CRD's API version coming soon https://github.com/operator-framework/operator-sdk/issues/1541 https://github.com/operator-framework/operator-sdk/pull/1680 the memcached-operator should have an example of multiple api versions with a CRD manifest that uses the `versions` field and a conversion webhook that handles conversions between the two apiversions.

Currently blocked by the proposal for scaffolding webhooks in the SDK https://github.com/operator-framework/operator-sdk/pull/1455 which is waiting on the `v0.2.0` release of the controller-runtime.

**Comment by camilamacedo86** [comment]
Closing this one since because we decided to make a proposal with the suggestions for this repo. I will add this topic as well. I will add this on the proposal too and link your issue. 

However, please feel to re-open if you think that it will be a better approach.

**Comment by camilamacedo86** [comment]
Hi @hasbro17, 

I am closing this one since shows outdated. However, please feel free to re-open if you see that it still required.
