### ISSUE TITLE
Where is webhook.Service defined?

### ISSUE THREAD

**Issue by r0fls** [operator-framework/operator-sdk-samples#70]
I see https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/vendor/sigs.k8s.io/controller-runtime/example/main.go#L120

But I can't find where `webhook.Service` is defined anywhere. It's not listed here for instance: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/webhook

I'm just trying to discover which parameters it takes.

**Comment by mhrivnak** [comment]
It's [present in 0.1 releases](https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.1/pkg/webhook/server.go#L104-L113), but not in the 0.2 line. The godoc link is pulling from `master`, which is the 0.2 line.

**Comment by r0fls** [comment]
Thanks!

**Comment by r0fls** [comment]
It looks like it's not possible to inject labels onto the service being created, is that correct? We need this in our environment because we enforce labelling requirements.
