### ISSUE TITLE
[Go samples] - Add CI tests

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk-samples#86]
We should add CI tests to verify the changes in the samples

**Comment by estroz** [comment]
We could fairly easily set up travis CI in this repo, at least for memcached-operator. Not sure about the others as they haven't been touched in a while.

**Comment by camilamacedo86** [comment]
HI @estroz, 

My idea was we started from GO. After we can check the other types as well. But I think that all samples should be covered by tests and be using coveralls in order to provide a really good sample and show indeed how the uses can use the test-framework too.

**Comment by camilamacedo86** [comment]
Closing this one since because we decided to make a proposal with the suggestions for this repo. I will add this topic as well.
