### ISSUE TITLE
Provide docker images for the samples

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk-samples#88]
**Description**
Instead of we have REPLACE_IMAGE in the samples we could have the docker images which should be used with. Also, these images should be changed/tagged and pushed after each release/sample upgrade.

PS.: I think that would be helpful impl first https://github.com/operator-framework/operator-sdk-samples/issues/86

**Comment by estroz** [comment]
This is a possibility especially if we get CI running for this repo; we could build a new image on every commit and release.

@hasbro17 wdyt about hosting this in quay.io/operator-framework?

**Comment by camilamacedo86** [comment]
HI @estroz this is my idea. We just need a docker/quayio operator-sdk or operator-framework account and do as it is done here in my personal projec: https://github.com/dev4devs-com/postgresql-operator/blob/master/.circleci/config.yml#L26 . Also see [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/Makefile#L83) the makefile target.

**Comment by camilamacedo86** [comment]
Closing this one since because we decided to make a proposal with the suggestions for this repo. I will add this topic as well.
