### ISSUE TITLE
Error when creating memcached crd

### ISSUE THREAD

**Issue by vazirim** [operator-framework/operator-sdk-samples#95]
I followed the instructions for installing the memcached-operator.
When I do `make install`, I get the following error:

```
....... Applying CRDS and Operator .......
kubectl apply -f deploy/crds/cache.example.com_memcacheds_crd.yaml -n memcached
The CustomResourceDefinition "memcacheds.cache.example.com" is invalid: spec.validation.openAPIV3Schema.properties[status].properties[nodes].uniqueItems: Forbidden: uniqueItems cannot be set to true since the runtime complexity becomes quadratic
```

**Comment by camilamacedo86** [comment]
Hi @vazirim, 

I assume you are checking the  Go type. Note that the version there is for the SDK 0.11 and go version 1.12+ and an older version of k8s api. So, it shows your problem. 

Use the https://github.com/operator-framework/operator-sdk-samples/pull/90 that it will be solved. 

In this way, I am closing this one. However, please feel free to re-open if you think that it is required.
